import os
print("""
\x1b[38;2;255;20;147m  ____        ___       _____ _       ___ _
 / ___|_  __ |_ _|_ __ |  ___(_)_ __ |_ _| |_ _   _
| |  _\ \/ /  | || '_ \| |_  | | '_ \ | || __| | | |
\033[37m| |_| |>  <   | || | | |  _| | | | | || || |_| |_| |
\033[35m \____/_/\_\ |___|_| |_|_|   |_|_| |_|___|\__|\__, |
                                              |___/
\033[0;91m⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⣠⠒⠀⠀⠀⡴⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣶⠞⠋⠉⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⢰⠁⠀⠀⠀⢰⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣿⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢀⡟⠀⠀⠀⠀⣿⠂⠀⠀⠀⠀⣀⠄⡴⢈⣤⣎⠴⡏⠀⣀⠄⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⢸⣧⠀⠀⠀⠀⣿⠃⠀⠀⠀⡞⠀⣼⣽⣷⡿⡣⣾⣿⣶⣿⣶⡶⠖⠄⠂⠀⠀⠀
⠀⠀⢠⠀⢸⣿⠀⠀⠀⢀⢹⣆⢀⣀⠀⣆⣾⣻⢞⡿⣺⣿⡿⠿⠛⠛⠻⢿⣿⣶⣄⠀⠀⠀
⠀⠀⣯⠀⠘⣼⢢⣰⣇⣼⣾⣯⢹⢿⣶⣿⡿⣱⣿⡥⠃⣁⠤⣤⡤⡀⠀⠀⠈⣿⠏⠀⠀⠀
⠀⠀⠸⣧⡀⣹⣬⢿⡟⢿⢿⠿⣿⢻⡅⣾⣾⣏⡎⡴⠊⣀⠀⢈⣿⣾⠂⠀⢰⠿⠀⠀⠀⠀
⠀⠀⠀⠙⢿⣺⡜⢸⣿⣿⢘⡶⢵⣿⡿⣸⢿⣷⣞⣗⣺⣟⣿⠯⡶⠊⠀⣠⣣⠃⠀⠀⠀⠀
⠀⠀⠀⠐⠦⢛⠿⣾⣿⣛⣾⣶⣿⢿⣿⡛⣯⣽⣻⣿⡟⢿⣳⠟⠁⢀⣞⡕⠁⠀⠀⠀⠀⠀
⠀⠀⢠⠀⠀⡀⠳⣾⣿⣿⡿⣿⣷⣽⣯⣶⠾⢿⣿⣽⠼⠊⠀⢀⣴⡿⠽⠩⣇⣄⠀⠀⠀⠀
⠀⠀⢠⣷⣸⣿⣇⡈⣿⣿⣿⣿⣿⣻⣞⣿⠟⠋⠉⠙⠀⢀⣴⢹⣿⣷⢿⣛⡏⠉⠀⠀⠀⠀
⠀⠀⣾⣯⠛⠸⣞⣻⣯⢽⣴⣿⡟⣿⢹⡏⠀⢀⣤⠀⣴⣻⢿⣿⣿⡋⢤⠗⠀⠀⠀⠀⠀⠀
⢀⡀⠘⣿⡷⠋⠀⠻⢼⣟⠟⠃⢹⣿⣿⠀⢸⡿⠃⣾⣿⣿⢸⢽⣿⠛⠉⠀⡀⣤⡤⠂⠀⠀
⠸⣙⠤⡞⠀⠀⠀⡠⠔⠒⠂⢤⡘⠙⣻⠀⠘⣷⢰⢿⣟⣺⣟⣊⠉⢠⠤⣾⠞⡽⠧⢤⣀⡀
⠀⡯⣦⠁⠀⠀⣾⠀⠀⠀⠀⠀⣈⣲⣾⠀⠀⠈⠺⡾⣍⣫⠙⡳⣷⣏⠞⠉⠁⠈⠑⡽⡆⠀
⠀⠹⣦⡀⠀⠀⡿⣦⣄⣠⣴⠟⠉⠀⠈⡄⠀⠀⠀⠙⠮⣏⣙⠿⠓⠁⠀⠀⢀⣀⣀⣷⡇⠀
⠀⠀⠙⣧⡀⠀⠘⠾⠾⠼⠋⠀⠀⠀⠀⣸⣆⡀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠞⠃⠀⠐⣱⠁⠀
⠀⠀⠀⠀⠑⢄⠀⠀⠀⠀⠀⠀⠀⣠⠞⢿⢿⡟⠢⠤⣀⣀⣀⣀⣤⣚⣶⠤⣤⡤⠚⠁⠀⠀
⠀⠀⠀⠠⢔⣲⠿⠗⢲⣴⢶⣚⡩⠄⣱⡼⣮⡇⠀⠀⣀⠬⢻⢗⣟⣿⣵⠶⣳⠾⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠘⠢⠜⠋⢺⠏⠐⠪⠭⣙⣭⣟⡿⠷⣊⡱⢠⢾⡞⠚⠉⠛⠉⠁⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠃⠀⠀⠀⣔⢓⣒⣉⠩⣭⣟⠋⣿⣏⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⣏⠋⡿⠚⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
""")

print("""\33[0;32m[1] RUN\n[2] CANCEL\nWhich One Do You Use?""")

c = input(">>>: ")
if c == "1":
    os.system(f'rm -rf .randomstring')
    os.system(f'rm -rf .resources')
    os.system(f'rm -rf .GODZILLA')
    os.system(f'rm -rf .ARCH')
    os.system(f'rm -rf .SSL')
    os.system(f'rm -rf .BOT')
    os.system(f'rm -rf .SSL2')
    os.system(f'rm -rf .ARCH2')
    os.system(f'rm -rf .MALWARE')
    os.system(f'rm -rf .TC1')
    os.system(f'rm -rf .TC2')
    os.system(f'rm -rf .BF')
    os.system(f'rm -rf .BF2')
    os.system(f'rm -rf .BF3')
    os.system(f'rm -rf .OV')
    os.system(f'rm -rf .OV2')
    os.system(f'unzip BOT.zip')
    os.system(f'rm -rf BOT.zip')
    os.system(f'unzip SSL2.zip')
    os.system(f'rm -rf SSL2.zip')
    os.system(f'unzip ARCH2.zip')
    os.system(f'rm -rf ARCH2.zip')
    os.system(f'unzip MALWARE.zip')
    os.system(f'rm -rf MALWARE.zip')
    os.system(f'unzip randomstring.zip')
    os.system(f'rm -rf randomstring.zip')
    os.system(f'unzip resources.zip')
    os.system(f'rm -rf resources.zip')
    os.system(f'unzip GODZILLA.zip')
    os.system(f'rm -rf GODZILLA.zip')
    os.system(f'unzip ARCH.zip')
    os.system(f'rm -rf ARCH.zip')
    os.system(f'unzip SSL.zip')
    os.system(f'rm -rf SSL.zip')    
    os.system(f'unzip TC1.zip')
    os.system(f'rm -rf TC1.zip')
    os.system(f'unzip TC2.zip')
    os.system(f'rm -rf TC2.zip')
    os.system(f'unzip BF.zip')
    os.system(f'rm -rf BF.zip')
    os.system(f'unzip BF2.zip')
    os.system(f'rm -rf BF2.zip')
    os.system(f'unzip BF3.zip')
    os.system(f'rm -rf BF3.zip')
    os.system(f'unzip OV.zip')
    os.system(f'rm -rf OV.zip')
    os.system(f'unzip OV2.zip')
    os.system(f'rm -rf OV2.zip')
    os.system(f'mv randomstring .randomstring')
    os.system(f'mv resources .resources')
    os.system(f'mv GODZILLA .GODZILLA')
    os.system(f'mv ARCH .ARCH')
    os.system(f'mv SSL .SSL')
    os.system(f'mv BOT .BOT')
    os.system(f'mv SSL2 .SSL2')
    os.system(f'mv ARCH2 .ARCH2')
    os.system(f'mv MALWARE .MALWARE')
    os.system(f'mv TC1 .TC1')
    os.system(f'mv TC2 .TC2')
    os.system(f'mv BF .BF')
    os.system(f'mv BF2 .BF2')
    os.system(f'mv BF3 .BF3')
    os.system(f'mv OV .OV')
    os.system(f'mv OV2 .OV2')
    os.system(f'cp node_modules.zip /root/GX/.BF')
    os.system(f'cp node_modules.zip /root/GX/.BF2')
    os.system(f'cp node_modules.zip /root/GX/.BF3')
    os.system(f'cp node_modules.zip /root/GX/.OV')
    os.system(f'cp node_modules.zip /root/GX/.OV2')
    os.system(f'cd .OV && unzip node_modules.zip && rm -rf node_modules.zip')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .OV2 && unzip node_modules.zip && rm -rf node_modules.zip')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF && unzip node_modules.zip && rm -rf node_modules.zip')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF2 && unzip node_modules.zip && rm -rf node_modules.zip')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF3 && unzip node_modules.zip && rm -rf node_modules.zip')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && bash install.sh')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .GODZILLA && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .randomstring && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .ARCH && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .SSL && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .SSL2 && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .ARCH2 && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .MALWARE && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .TC1 && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .TC2 && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF2 && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF3 && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .OV && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .OV2 && ulimit -n 999999 && chmod 777 *')
    os.system("cd")
    os.system(f'cd /media && rm -rf *')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF && cp BROWSER /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF && cp BROWSER3.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF2 && cp BROWSER1 /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF2 && cp BROWSER4.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF3 && cp BROWSER2.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF3 && cp hui.txt /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .BF3 && cp BROWSER5.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .GODZILLA && cp HTTP.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .GODZILLA && cp HTTP-RAND.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .GODZILLA && cp tls /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .GODZILLA && cp tlsv2.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .randomstring && cp input.py /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .randomstring && cp referers.txt /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .randomstring && cp screetvip /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .OV && cp OVER.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .OV && cp OVER2.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .OV && cp OVER3.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .OV2 && cp OVER4.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .OV2 && cp OVER5.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .OV2 && cp OVER6.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .randomstring && cp user-agent.txt /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .SSL && cp passkey /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp count.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp http.txt /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp install.sh /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp ua.txt /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp Hulk.go /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp Low.go /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp strike.go /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp RAW /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp TCP /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp requirements.txt /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp uambypass.js /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp proxy.txt /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp proxies.txt /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp http.txt /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cd .resources && cp socks5.txt /media')
    os.system("cd")
    os.system("cd GX")
    os.system(f'cp node_modules.zip /media')
    os.system("cd")
    os.system(f'cd /media && unzip node_modules.zip')
    os.system("cd")
    os.system(f'cd /media && bash install.sh')
    os.system("cd")
    os.system(f'cd /media && rm -rf node_modules.zip')
    os.system("cd")
    os.system(f'cd /media && ulimit -n 999999')
    os.system("cd")
    os.system(f'cd /media && unzip chmod 777 *')
    os.system("cd")
    os.system("cd GX")
    os.system("python3 x.py")

elif c == "2":
    os.system("clear")

print("\33[0;32m[ √ ]PENGINSTALAN MODUL DI BATALKAN                                                                                                             ⚠️JIKA MODUL ZIP SUDAH JADI FOLDER JANGAN PERNAH INSTALL LAGI JIKA ANDA TIDAK INGIN KE HILANGAN MODUL LAGI!")